import { ChatRole } from '@/types';
import { SearchResult } from './search.model';

/**
 * Defines the specific task context for the Chat Provider request.
 */
export type ChatTask = 'query-transformation' | 'reranking' | 'chat' | 'crag-evaluation';

/**
 * Represents an individual message in a chat conversation.
 */
export interface ChatMessage {
  readonly role: ChatRole;
  readonly content: string;
}

/**
 * Represents the response generated by the AI chat provider, including grounded sources.
 */
export interface ChatResponse {
  readonly message: ChatMessage;
  readonly sources?: readonly SearchResult[];
}

/**
 * Represents an incremental piece of the generated response during streaming.
 */
export interface ChatChunk {
  readonly content: string;
  readonly done: boolean;
}
