import { ChatRole } from '@/types';
import { SearchResult } from './search.model';

/**
 * Represents an individual message in a chat conversation.
 */
export interface ChatMessage {
  readonly role: ChatRole;
  readonly content: string;
}

/**
 * Represents the response generated by the AI chat provider, including grounded sources.
 */
export interface ChatResponse {
  readonly message: ChatMessage;
  readonly sources?: readonly SearchResult[];
}
